// Mocks generated by Mockito 5.4.6 from annotations
// in adptydemo/test/adapty_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:adapty_flutter/src/adapty.dart' as _i5;
import 'package:adapty_flutter/src/models/adapty_access_level.dart' as _i19;
import 'package:adapty_flutter/src/models/adapty_configuration.dart' as _i9;
import 'package:adapty_flutter/src/models/adapty_error.dart' as _i8;
import 'package:adapty_flutter/src/models/adapty_installation_details.dart'
    as _i7;
import 'package:adapty_flutter/src/models/adapty_log_level.dart' as _i10;
import 'package:adapty_flutter/src/models/adapty_non_subscription.dart' as _i21;
import 'package:adapty_flutter/src/models/adapty_onboarding.dart' as _i4;
import 'package:adapty_flutter/src/models/adapty_paywall.dart' as _i3;
import 'package:adapty_flutter/src/models/adapty_paywall_fetch_policy.dart'
    as _i13;
import 'package:adapty_flutter/src/models/adapty_paywall_product.dart' as _i14;
import 'package:adapty_flutter/src/models/adapty_profile.dart' as _i2;
import 'package:adapty_flutter/src/models/adapty_profile_parameters.dart'
    as _i12;
import 'package:adapty_flutter/src/models/adapty_purchase_parameters.dart'
    as _i16;
import 'package:adapty_flutter/src/models/adapty_purchase_result.dart' as _i15;
import 'package:adapty_flutter/src/models/adapty_refund_preference.dart'
    as _i18;
import 'package:adapty_flutter/src/models/adapty_subscription.dart' as _i20;
import 'package:adapty_flutter/src/models/adapty_web_presentation.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdaptyProfile_0 extends _i1.SmartFake implements _i2.AdaptyProfile {
  _FakeAdaptyProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyPaywall_1 extends _i1.SmartFake implements _i3.AdaptyPaywall {
  _FakeAdaptyPaywall_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyOnboarding_2 extends _i1.SmartFake
    implements _i4.AdaptyOnboarding {
  _FakeAdaptyOnboarding_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Adapty].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdapty extends _i1.Mock implements _i5.Adapty {
  @override
  _i6.Stream<_i2.AdaptyProfile> get didUpdateProfileStream =>
      (super.noSuchMethod(
            Invocation.getter(#didUpdateProfileStream),
            returnValue: _i6.Stream<_i2.AdaptyProfile>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.AdaptyProfile>.empty(),
          )
          as _i6.Stream<_i2.AdaptyProfile>);

  @override
  _i6.Stream<_i7.AdaptyInstallationDetails>
  get onUpdateInstallationDetailsSuccessStream =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdateInstallationDetailsSuccessStream),
            returnValue: _i6.Stream<_i7.AdaptyInstallationDetails>.empty(),
            returnValueForMissingStub:
                _i6.Stream<_i7.AdaptyInstallationDetails>.empty(),
          )
          as _i6.Stream<_i7.AdaptyInstallationDetails>);

  @override
  _i6.Stream<_i8.AdaptyError> get onUpdateInstallationDetailsFailStream =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdateInstallationDetailsFailStream),
            returnValue: _i6.Stream<_i8.AdaptyError>.empty(),
            returnValueForMissingStub: _i6.Stream<_i8.AdaptyError>.empty(),
          )
          as _i6.Stream<_i8.AdaptyError>);

  @override
  _i6.Future<bool> isActivated() =>
      (super.noSuchMethod(
            Invocation.method(#isActivated, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setupAfterHotRestart() => super.noSuchMethod(
    Invocation.method(#setupAfterHotRestart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> activate({
    required _i9.AdaptyConfiguration? configuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activate, [], {#configuration: configuration}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setLogLevel(_i10.AdaptyLogLevel? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.AdaptyInstallationStatus> getCurrentInstallationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentInstallationStatus, []),
            returnValue: _i6.Future<_i7.AdaptyInstallationStatus>.value(
              _i11.dummyValue<_i7.AdaptyInstallationStatus>(
                this,
                Invocation.method(#getCurrentInstallationStatus, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.AdaptyInstallationStatus>.value(
                  _i11.dummyValue<_i7.AdaptyInstallationStatus>(
                    this,
                    Invocation.method(#getCurrentInstallationStatus, []),
                  ),
                ),
          )
          as _i6.Future<_i7.AdaptyInstallationStatus>);

  @override
  _i6.Future<_i2.AdaptyProfile> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(this, Invocation.method(#getProfile, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i6.Future<_i2.AdaptyProfile>);

  @override
  _i6.Future<void> updateProfile(_i12.AdaptyProfileParameters? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [params]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> identify(
    String? customerUserId, {
    String? iosAppAccountToken,
    String? androidObfuscatedAccountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #identify,
              [customerUserId],
              {
                #iosAppAccountToken: iosAppAccountToken,
                #androidObfuscatedAccountId: androidObfuscatedAccountId,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AdaptyPaywall> getPaywallForDefaultAudience({
    required String? placementId,
    String? locale,
    _i13.AdaptyPaywallFetchPolicy? fetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywallForDefaultAudience, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
            }),
            returnValue: _i6.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywallForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywallForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AdaptyPaywall>);

  @override
  _i6.Future<_i3.AdaptyPaywall> getPaywall({
    required String? placementId,
    String? locale,
    _i13.AdaptyPaywallFetchPolicy? fetchPolicy,
    Duration? loadTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywall, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
              #loadTimeout: loadTimeout,
            }),
            returnValue: _i6.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywall, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywall, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AdaptyPaywall>);

  @override
  _i6.Future<List<_i14.AdaptyPaywallProduct>> getPaywallProducts({
    required _i3.AdaptyPaywall? paywall,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywallProducts, [], {#paywall: paywall}),
            returnValue: _i6.Future<List<_i14.AdaptyPaywallProduct>>.value(
              <_i14.AdaptyPaywallProduct>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i14.AdaptyPaywallProduct>>.value(
                  <_i14.AdaptyPaywallProduct>[],
                ),
          )
          as _i6.Future<List<_i14.AdaptyPaywallProduct>>);

  @override
  _i6.Future<_i4.AdaptyOnboarding> getOnboarding({
    required String? placementId,
    String? locale,
    _i13.AdaptyPaywallFetchPolicy? fetchPolicy,
    Duration? loadTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOnboarding, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
              #loadTimeout: loadTimeout,
            }),
            returnValue: _i6.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboarding, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboarding, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AdaptyOnboarding>);

  @override
  _i6.Future<_i4.AdaptyOnboarding> getOnboardingForDefaultAudience({
    required String? placementId,
    String? locale,
    _i13.AdaptyPaywallFetchPolicy? fetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingForDefaultAudience, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
            }),
            returnValue: _i6.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboardingForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboardingForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AdaptyOnboarding>);

  @override
  _i6.Future<_i15.AdaptyPurchaseResult> makePurchase({
    required _i14.AdaptyPaywallProduct? product,
    _i16.AdaptyPurchaseParameters? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#makePurchase, [], {
              #product: product,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<_i15.AdaptyPurchaseResult>.value(
              _i11.dummyValue<_i15.AdaptyPurchaseResult>(
                this,
                Invocation.method(#makePurchase, [], {
                  #product: product,
                  #parameters: parameters,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i15.AdaptyPurchaseResult>.value(
                  _i11.dummyValue<_i15.AdaptyPurchaseResult>(
                    this,
                    Invocation.method(#makePurchase, [], {
                      #product: product,
                      #parameters: parameters,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i15.AdaptyPurchaseResult>);

  @override
  _i6.Future<_i2.AdaptyProfile> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i6.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
          )
          as _i6.Future<_i2.AdaptyProfile>);

  @override
  _i6.Future<void> setIntegrationIdentifier({
    required String? key,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setIntegrationIdentifier, [], {
              #key: key,
              #value: value,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateAttribution(
    Map<dynamic, dynamic>? attribution, {
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAttribution,
              [attribution],
              {#source: source},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logShowPaywall({required _i3.AdaptyPaywall? paywall}) =>
      (super.noSuchMethod(
            Invocation.method(#logShowPaywall, [], {#paywall: paywall}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reportTransaction({
    required String? transactionId,
    String? variationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportTransaction, [], {
              #transactionId: transactionId,
              #variationId: variationId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setFallbackPaywalls(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#setFallbackPaywalls, [assetId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setFallback(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#setFallback, [assetId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> createWebPaywallUrl({
    _i3.AdaptyPaywall? paywall,
    _i14.AdaptyPaywallProduct? product,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWebPaywallUrl, [], {
              #paywall: paywall,
              #product: product,
            }),
            returnValue: _i6.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createWebPaywallUrl, [], {
                  #paywall: paywall,
                  #product: product,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createWebPaywallUrl, [], {
                  #paywall: paywall,
                  #product: product,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> openWebPaywall({
    _i3.AdaptyPaywall? paywall,
    _i14.AdaptyPaywallProduct? product,
    _i17.AdaptyWebPresentation? openIn =
        _i17.AdaptyWebPresentation.externalBrowser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWebPaywall, [], {
              #paywall: paywall,
              #product: product,
              #openIn: openIn,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateCollectingRefundDataConsent(bool? consent) =>
      (super.noSuchMethod(
            Invocation.method(#updateCollectingRefundDataConsent, [consent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRefundPreference(
    _i18.AdaptyRefundPreference? refundPreference,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRefundPreference, [refundPreference]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> presentCodeRedemptionSheet() =>
      (super.noSuchMethod(
            Invocation.method(#presentCodeRedemptionSheet, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AdaptyProfile].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyProfile extends _i1.Mock implements _i2.AdaptyProfile {
  @override
  String get profileId =>
      (super.noSuchMethod(
            Invocation.getter(#profileId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#profileId),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#profileId),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get customAttributes =>
      (super.noSuchMethod(
            Invocation.getter(#customAttributes),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, _i19.AdaptyAccessLevel> get accessLevels =>
      (super.noSuchMethod(
            Invocation.getter(#accessLevels),
            returnValue: <String, _i19.AdaptyAccessLevel>{},
            returnValueForMissingStub: <String, _i19.AdaptyAccessLevel>{},
          )
          as Map<String, _i19.AdaptyAccessLevel>);

  @override
  Map<String, _i20.AdaptySubscription> get subscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptions),
            returnValue: <String, _i20.AdaptySubscription>{},
            returnValueForMissingStub: <String, _i20.AdaptySubscription>{},
          )
          as Map<String, _i20.AdaptySubscription>);

  @override
  Map<String, List<_i21.AdaptyNonSubscription>> get nonSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#nonSubscriptions),
            returnValue: <String, List<_i21.AdaptyNonSubscription>>{},
            returnValueForMissingStub:
                <String, List<_i21.AdaptyNonSubscription>>{},
          )
          as Map<String, List<_i21.AdaptyNonSubscription>>);

  @override
  bool get isTestUser =>
      (super.noSuchMethod(
            Invocation.getter(#isTestUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AdaptyAccessLevel].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyAccessLevel extends _i1.Mock implements _i19.AdaptyAccessLevel {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get vendorProductId =>
      (super.noSuchMethod(
            Invocation.getter(#vendorProductId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
          )
          as String);

  @override
  String get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#store),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#store),
            ),
          )
          as String);

  @override
  DateTime get activatedAt =>
      (super.noSuchMethod(
            Invocation.getter(#activatedAt),
            returnValue: _FakeDateTime_3(this, Invocation.getter(#activatedAt)),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.getter(#activatedAt),
            ),
          )
          as DateTime);

  @override
  bool get isLifetime =>
      (super.noSuchMethod(
            Invocation.getter(#isLifetime),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get willRenew =>
      (super.noSuchMethod(
            Invocation.getter(#willRenew),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInGracePeriod =>
      (super.noSuchMethod(
            Invocation.getter(#isInGracePeriod),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRefund =>
      (super.noSuchMethod(
            Invocation.getter(#isRefund),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
