// Mocks generated by Mockito 5.4.6 from annotations
// in adptydemo/test/adapty_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:adapty_flutter/src/adapty.dart' as _i7;
import 'package:adapty_flutter/src/models/adapty_access_level.dart' as _i21;
import 'package:adapty_flutter/src/models/adapty_configuration.dart' as _i11;
import 'package:adapty_flutter/src/models/adapty_error.dart' as _i10;
import 'package:adapty_flutter/src/models/adapty_installation_details.dart'
    as _i9;
import 'package:adapty_flutter/src/models/adapty_log_level.dart' as _i12;
import 'package:adapty_flutter/src/models/adapty_non_subscription.dart' as _i23;
import 'package:adapty_flutter/src/models/adapty_onboarding.dart' as _i4;
import 'package:adapty_flutter/src/models/adapty_paywall.dart' as _i3;
import 'package:adapty_flutter/src/models/adapty_paywall_fetch_policy.dart'
    as _i15;
import 'package:adapty_flutter/src/models/adapty_paywall_product.dart' as _i16;
import 'package:adapty_flutter/src/models/adapty_placement.dart' as _i5;
import 'package:adapty_flutter/src/models/adapty_price.dart' as _i6;
import 'package:adapty_flutter/src/models/adapty_product_identifier.dart'
    as _i24;
import 'package:adapty_flutter/src/models/adapty_profile.dart' as _i2;
import 'package:adapty_flutter/src/models/adapty_profile_parameters.dart'
    as _i14;
import 'package:adapty_flutter/src/models/adapty_purchase_parameters.dart'
    as _i18;
import 'package:adapty_flutter/src/models/adapty_purchase_result.dart' as _i17;
import 'package:adapty_flutter/src/models/adapty_refund_preference.dart'
    as _i20;
import 'package:adapty_flutter/src/models/adapty_subscription.dart' as _i22;
import 'package:adapty_flutter/src/models/adapty_web_presentation.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdaptyProfile_0 extends _i1.SmartFake implements _i2.AdaptyProfile {
  _FakeAdaptyProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyPaywall_1 extends _i1.SmartFake implements _i3.AdaptyPaywall {
  _FakeAdaptyPaywall_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyOnboarding_2 extends _i1.SmartFake
    implements _i4.AdaptyOnboarding {
  _FakeAdaptyOnboarding_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyPlacement_4 extends _i1.SmartFake
    implements _i5.AdaptyPlacement {
  _FakeAdaptyPlacement_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdaptyPrice_5 extends _i1.SmartFake implements _i6.AdaptyPrice {
  _FakeAdaptyPrice_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Adapty].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdapty extends _i1.Mock implements _i7.Adapty {
  @override
  _i8.Stream<_i2.AdaptyProfile> get didUpdateProfileStream =>
      (super.noSuchMethod(
            Invocation.getter(#didUpdateProfileStream),
            returnValue: _i8.Stream<_i2.AdaptyProfile>.empty(),
            returnValueForMissingStub: _i8.Stream<_i2.AdaptyProfile>.empty(),
          )
          as _i8.Stream<_i2.AdaptyProfile>);

  @override
  _i8.Stream<_i9.AdaptyInstallationDetails>
  get onUpdateInstallationDetailsSuccessStream =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdateInstallationDetailsSuccessStream),
            returnValue: _i8.Stream<_i9.AdaptyInstallationDetails>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i9.AdaptyInstallationDetails>.empty(),
          )
          as _i8.Stream<_i9.AdaptyInstallationDetails>);

  @override
  _i8.Stream<_i10.AdaptyError> get onUpdateInstallationDetailsFailStream =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdateInstallationDetailsFailStream),
            returnValue: _i8.Stream<_i10.AdaptyError>.empty(),
            returnValueForMissingStub: _i8.Stream<_i10.AdaptyError>.empty(),
          )
          as _i8.Stream<_i10.AdaptyError>);

  @override
  _i8.Future<bool> isActivated() =>
      (super.noSuchMethod(
            Invocation.method(#isActivated, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void setupAfterHotRestart() => super.noSuchMethod(
    Invocation.method(#setupAfterHotRestart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> activate({
    required _i11.AdaptyConfiguration? configuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activate, [], {#configuration: configuration}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLogLevel(_i12.AdaptyLogLevel? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.AdaptyInstallationStatus> getCurrentInstallationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentInstallationStatus, []),
            returnValue: _i8.Future<_i9.AdaptyInstallationStatus>.value(
              _i13.dummyValue<_i9.AdaptyInstallationStatus>(
                this,
                Invocation.method(#getCurrentInstallationStatus, []),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i9.AdaptyInstallationStatus>.value(
                  _i13.dummyValue<_i9.AdaptyInstallationStatus>(
                    this,
                    Invocation.method(#getCurrentInstallationStatus, []),
                  ),
                ),
          )
          as _i8.Future<_i9.AdaptyInstallationStatus>);

  @override
  _i8.Future<_i2.AdaptyProfile> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i8.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(this, Invocation.method(#getProfile, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i8.Future<_i2.AdaptyProfile>);

  @override
  _i8.Future<void> updateProfile(_i14.AdaptyProfileParameters? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [params]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> identify(
    String? customerUserId, {
    String? iosAppAccountToken,
    String? androidObfuscatedAccountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #identify,
              [customerUserId],
              {
                #iosAppAccountToken: iosAppAccountToken,
                #androidObfuscatedAccountId: androidObfuscatedAccountId,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.AdaptyPaywall> getPaywallForDefaultAudience({
    required String? placementId,
    String? locale,
    _i15.AdaptyPaywallFetchPolicy? fetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywallForDefaultAudience, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
            }),
            returnValue: _i8.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywallForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywallForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.AdaptyPaywall>);

  @override
  _i8.Future<_i3.AdaptyPaywall> getPaywall({
    required String? placementId,
    String? locale,
    _i15.AdaptyPaywallFetchPolicy? fetchPolicy,
    Duration? loadTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywall, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
              #loadTimeout: loadTimeout,
            }),
            returnValue: _i8.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywall, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.AdaptyPaywall>.value(
              _FakeAdaptyPaywall_1(
                this,
                Invocation.method(#getPaywall, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.AdaptyPaywall>);

  @override
  _i8.Future<List<_i16.AdaptyPaywallProduct>> getPaywallProducts({
    required _i3.AdaptyPaywall? paywall,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaywallProducts, [], {#paywall: paywall}),
            returnValue: _i8.Future<List<_i16.AdaptyPaywallProduct>>.value(
              <_i16.AdaptyPaywallProduct>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i16.AdaptyPaywallProduct>>.value(
                  <_i16.AdaptyPaywallProduct>[],
                ),
          )
          as _i8.Future<List<_i16.AdaptyPaywallProduct>>);

  @override
  _i8.Future<_i4.AdaptyOnboarding> getOnboarding({
    required String? placementId,
    String? locale,
    _i15.AdaptyPaywallFetchPolicy? fetchPolicy,
    Duration? loadTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOnboarding, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
              #loadTimeout: loadTimeout,
            }),
            returnValue: _i8.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboarding, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboarding, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                  #loadTimeout: loadTimeout,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.AdaptyOnboarding>);

  @override
  _i8.Future<_i4.AdaptyOnboarding> getOnboardingForDefaultAudience({
    required String? placementId,
    String? locale,
    _i15.AdaptyPaywallFetchPolicy? fetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingForDefaultAudience, [], {
              #placementId: placementId,
              #locale: locale,
              #fetchPolicy: fetchPolicy,
            }),
            returnValue: _i8.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboardingForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.AdaptyOnboarding>.value(
              _FakeAdaptyOnboarding_2(
                this,
                Invocation.method(#getOnboardingForDefaultAudience, [], {
                  #placementId: placementId,
                  #locale: locale,
                  #fetchPolicy: fetchPolicy,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.AdaptyOnboarding>);

  @override
  _i8.Future<_i17.AdaptyPurchaseResult> makePurchase({
    required _i16.AdaptyPaywallProduct? product,
    _i18.AdaptyPurchaseParameters? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#makePurchase, [], {
              #product: product,
              #parameters: parameters,
            }),
            returnValue: _i8.Future<_i17.AdaptyPurchaseResult>.value(
              _i13.dummyValue<_i17.AdaptyPurchaseResult>(
                this,
                Invocation.method(#makePurchase, [], {
                  #product: product,
                  #parameters: parameters,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i17.AdaptyPurchaseResult>.value(
                  _i13.dummyValue<_i17.AdaptyPurchaseResult>(
                    this,
                    Invocation.method(#makePurchase, [], {
                      #product: product,
                      #parameters: parameters,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i17.AdaptyPurchaseResult>);

  @override
  _i8.Future<_i2.AdaptyProfile> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i8.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.AdaptyProfile>.value(
              _FakeAdaptyProfile_0(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
          )
          as _i8.Future<_i2.AdaptyProfile>);

  @override
  _i8.Future<void> setIntegrationIdentifier({
    required String? key,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setIntegrationIdentifier, [], {
              #key: key,
              #value: value,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateAttribution(
    Map<dynamic, dynamic>? attribution, {
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAttribution,
              [attribution],
              {#source: source},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logShowPaywall({required _i3.AdaptyPaywall? paywall}) =>
      (super.noSuchMethod(
            Invocation.method(#logShowPaywall, [], {#paywall: paywall}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reportTransaction({
    required String? transactionId,
    String? variationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportTransaction, [], {
              #transactionId: transactionId,
              #variationId: variationId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setFallbackPaywalls(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#setFallbackPaywalls, [assetId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setFallback(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#setFallback, [assetId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> createWebPaywallUrl({
    _i3.AdaptyPaywall? paywall,
    _i16.AdaptyPaywallProduct? product,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWebPaywallUrl, [], {
              #paywall: paywall,
              #product: product,
            }),
            returnValue: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createWebPaywallUrl, [], {
                  #paywall: paywall,
                  #product: product,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createWebPaywallUrl, [], {
                  #paywall: paywall,
                  #product: product,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> openWebPaywall({
    _i3.AdaptyPaywall? paywall,
    _i16.AdaptyPaywallProduct? product,
    _i19.AdaptyWebPresentation? openIn =
        _i19.AdaptyWebPresentation.externalBrowser,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWebPaywall, [], {
              #paywall: paywall,
              #product: product,
              #openIn: openIn,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateCollectingRefundDataConsent(bool? consent) =>
      (super.noSuchMethod(
            Invocation.method(#updateCollectingRefundDataConsent, [consent]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateRefundPreference(
    _i20.AdaptyRefundPreference? refundPreference,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRefundPreference, [refundPreference]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> presentCodeRedemptionSheet() =>
      (super.noSuchMethod(
            Invocation.method(#presentCodeRedemptionSheet, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AdaptyProfile].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyProfile extends _i1.Mock implements _i2.AdaptyProfile {
  @override
  String get profileId =>
      (super.noSuchMethod(
            Invocation.getter(#profileId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#profileId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#profileId),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get customAttributes =>
      (super.noSuchMethod(
            Invocation.getter(#customAttributes),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, _i21.AdaptyAccessLevel> get accessLevels =>
      (super.noSuchMethod(
            Invocation.getter(#accessLevels),
            returnValue: <String, _i21.AdaptyAccessLevel>{},
            returnValueForMissingStub: <String, _i21.AdaptyAccessLevel>{},
          )
          as Map<String, _i21.AdaptyAccessLevel>);

  @override
  Map<String, _i22.AdaptySubscription> get subscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptions),
            returnValue: <String, _i22.AdaptySubscription>{},
            returnValueForMissingStub: <String, _i22.AdaptySubscription>{},
          )
          as Map<String, _i22.AdaptySubscription>);

  @override
  Map<String, List<_i23.AdaptyNonSubscription>> get nonSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#nonSubscriptions),
            returnValue: <String, List<_i23.AdaptyNonSubscription>>{},
            returnValueForMissingStub:
                <String, List<_i23.AdaptyNonSubscription>>{},
          )
          as Map<String, List<_i23.AdaptyNonSubscription>>);

  @override
  bool get isTestUser =>
      (super.noSuchMethod(
            Invocation.getter(#isTestUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AdaptyAccessLevel].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyAccessLevel extends _i1.Mock implements _i21.AdaptyAccessLevel {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get vendorProductId =>
      (super.noSuchMethod(
            Invocation.getter(#vendorProductId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
          )
          as String);

  @override
  String get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#store),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#store),
            ),
          )
          as String);

  @override
  DateTime get activatedAt =>
      (super.noSuchMethod(
            Invocation.getter(#activatedAt),
            returnValue: _FakeDateTime_3(this, Invocation.getter(#activatedAt)),
            returnValueForMissingStub: _FakeDateTime_3(
              this,
              Invocation.getter(#activatedAt),
            ),
          )
          as DateTime);

  @override
  bool get isLifetime =>
      (super.noSuchMethod(
            Invocation.getter(#isLifetime),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get willRenew =>
      (super.noSuchMethod(
            Invocation.getter(#willRenew),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInGracePeriod =>
      (super.noSuchMethod(
            Invocation.getter(#isInGracePeriod),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRefund =>
      (super.noSuchMethod(
            Invocation.getter(#isRefund),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AdaptyPaywall].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyPaywall extends _i1.Mock implements _i3.AdaptyPaywall {
  @override
  _i5.AdaptyPlacement get placement =>
      (super.noSuchMethod(
            Invocation.getter(#placement),
            returnValue: _FakeAdaptyPlacement_4(
              this,
              Invocation.getter(#placement),
            ),
            returnValueForMissingStub: _FakeAdaptyPlacement_4(
              this,
              Invocation.getter(#placement),
            ),
          )
          as _i5.AdaptyPlacement);

  @override
  String get instanceIdentity =>
      (super.noSuchMethod(
            Invocation.getter(#instanceIdentity),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#instanceIdentity),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#instanceIdentity),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get variationId =>
      (super.noSuchMethod(
            Invocation.getter(#variationId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#variationId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#variationId),
            ),
          )
          as String);

  @override
  bool get hasViewConfiguration =>
      (super.noSuchMethod(
            Invocation.getter(#hasViewConfiguration),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i24.AdaptyProductIdentifier> get productIdentifiers =>
      (super.noSuchMethod(
            Invocation.getter(#productIdentifiers),
            returnValue: <_i24.AdaptyProductIdentifier>[],
            returnValueForMissingStub: <_i24.AdaptyProductIdentifier>[],
          )
          as List<_i24.AdaptyProductIdentifier>);

  @override
  List<String> get vendorProductIds =>
      (super.noSuchMethod(
            Invocation.getter(#vendorProductIds),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  String get placementId =>
      (super.noSuchMethod(
            Invocation.getter(#placementId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#placementId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#placementId),
            ),
          )
          as String);

  @override
  int get revision =>
      (super.noSuchMethod(
            Invocation.getter(#revision),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [AdaptyPaywallProduct].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAdaptyPaywallProduct extends _i1.Mock
    implements _i16.AdaptyPaywallProduct {
  @override
  String get vendorProductId =>
      (super.noSuchMethod(
            Invocation.getter(#vendorProductId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#vendorProductId),
            ),
          )
          as String);

  @override
  String get accessLevelId =>
      (super.noSuchMethod(
            Invocation.getter(#accessLevelId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#accessLevelId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#accessLevelId),
            ),
          )
          as String);

  @override
  String get productType =>
      (super.noSuchMethod(
            Invocation.getter(#productType),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#productType),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#productType),
            ),
          )
          as String);

  @override
  String get paywallVariationId =>
      (super.noSuchMethod(
            Invocation.getter(#paywallVariationId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallVariationId),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallVariationId),
            ),
          )
          as String);

  @override
  String get paywallABTestName =>
      (super.noSuchMethod(
            Invocation.getter(#paywallABTestName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallABTestName),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallABTestName),
            ),
          )
          as String);

  @override
  String get paywallName =>
      (super.noSuchMethod(
            Invocation.getter(#paywallName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallName),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#paywallName),
            ),
          )
          as String);

  @override
  String get localizedDescription =>
      (super.noSuchMethod(
            Invocation.getter(#localizedDescription),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#localizedDescription),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#localizedDescription),
            ),
          )
          as String);

  @override
  String get localizedTitle =>
      (super.noSuchMethod(
            Invocation.getter(#localizedTitle),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#localizedTitle),
            ),
            returnValueForMissingStub: _i13.dummyValue<String>(
              this,
              Invocation.getter(#localizedTitle),
            ),
          )
          as String);

  @override
  bool get isFamilyShareable =>
      (super.noSuchMethod(
            Invocation.getter(#isFamilyShareable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.AdaptyPrice get price =>
      (super.noSuchMethod(
            Invocation.getter(#price),
            returnValue: _FakeAdaptyPrice_5(this, Invocation.getter(#price)),
            returnValueForMissingStub: _FakeAdaptyPrice_5(
              this,
              Invocation.getter(#price),
            ),
          )
          as _i6.AdaptyPrice);

  @override
  int get paywallProductIndex =>
      (super.noSuchMethod(
            Invocation.getter(#paywallProductIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [AdaptyPurchaseResultPending].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptyPurchaseResultPending extends _i1.Mock
    implements _i17.AdaptyPurchaseResultPending {}

/// A class which mocks [AdaptyPurchaseResultUserCancelled].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptyPurchaseResultUserCancelled extends _i1.Mock
    implements _i17.AdaptyPurchaseResultUserCancelled {}

/// A class which mocks [AdaptyPurchaseResultSuccess].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptyPurchaseResultSuccess extends _i1.Mock
    implements _i17.AdaptyPurchaseResultSuccess {
  @override
  _i2.AdaptyProfile get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _FakeAdaptyProfile_0(
              this,
              Invocation.getter(#profile),
            ),
            returnValueForMissingStub: _FakeAdaptyProfile_0(
              this,
              Invocation.getter(#profile),
            ),
          )
          as _i2.AdaptyProfile);
}
